name: Excel to CSV and HTML Conversion

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at 00:00 UTC
  workflow_dispatch: # Add this line to allow manual triggering 

jobs:
  excel_conversion:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl lxml selenium

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
          
      - name: Run Python script
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CSV and HTML files
          file_pattern: '*.csv,*.html'
          branch: main

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: converted-files
          path: |
            *.csv
            *.html
            
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG_NAME: ${{ format('release-{0}', env.DATE) }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false